CryptoNews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crypto.urls', namespace='crypto')),
]

crypto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView, PriceView

app_name = 'crypto'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path("prices/", PriceView.as_view(), name='prices'),
]

crypto/models.py
from django.db import models

# Create your models here.

crypto/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views import View
import requests
import json


# Create your views here.
class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Grab Crypto News
        news_api_request = requests.get('https://min-api.cryptocompare.com/data/v2/news/?lang=EN')
        context['news'] = json.loads(news_api_request.content)

        # Grab Crypto Price Data
        price_api_request = requests.get('https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,BCH,EOS,LTC,LINK,ETC,SXP&tsyms=USD')
        context['price'] = json.loads(price_api_request.content)

        return context


class PriceView(View):
    template_name = 'search_prices.html'

    def get(self,request,*args,**kwargs):
        prices_api_request = requests.get('https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,BCH,EOS,LTC,LINK,ETC,SXP,LINK,VET,&tsyms=USD,EUR,JPY,BDT')

        context = {
            'crypto': json.loads(prices_api_request.content),
        }
        return render(request, "all_prices.html", context)

    def post(self,request,*args,**kwargs):
        if request.POST['quote']:
            quote = (request.POST['quote']).upper()
            quote_api_request = requests.get(f'https://min-api.cryptocompare.com/data/pricemultifull?fsyms={quote}&tsyms=USD,BDT')

            context = {
                'crypto':  json.loads(quote_api_request.content),
                'quotes':  quote,
            }
            return render(request, self.template_name, context)

        else:
            context = {
                "message": "Enter a valid crypto currency short name"
            }
            return render(request, self.template_name, context)

templates/all_prices.html
{% extends 'base.html' %}

{% block content %}
    {#      Crypto Price Table Start     #}
    <h4>Currency Comparison</h4>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th scope="col">Crypto</th>
                <th scope="col">USD</th>
                <th scope="col">BDT</th>
                <th scope="col">EUR</th>
                <th scope="col">JPY</th>
            </tr>
            </thead>
            <tbody>
            {% for key,value in crypto.DISPLAY.items %}
                <tr>
                    <td>{{key}}</td>
                    <td>{{ value.USD.PRICE }}</td>
                    <td>{{ value.BDT.PRICE }}</td>
                    <td>{{ value.EUR.PRICE }}</td>
                    <td>{{ value.JPY.PRICE }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {#      Crypto Price Table End     #}

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Crypto News</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'crypto:home' %}">Crypto World</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'crypto:prices' %}">Lookup Prices</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'crypto:prices' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="quote">
            <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Lookup Crypto</button>
        </form>
    </div>
</nav>
<br/>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {#      Jumbotron Start     #}
    <div class="jumbotron">
        <h1 class="display-4">Welcome To Crypto World</h1>
        <p class="lead">All the latest news about Crypto Currency and Blockchain </p>
        </p>
    </div>
    {#      Jumbotron end     #}

    {#      Crypto Price Table Start     #}
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
            <th scope="col">Crypto</th>
            <th scope="col">Price</th>
            <th scope="col">24h High</th>
            <th scope="col">24h Low</th>
            <th scope="col">Market Cap</th>
        </tr>
        </thead>
        <tbody>
        {% for key,value in price.DISPLAY.items %}
            <tr>
                <td>{{key}}</td>
                <td>{{ value.USD.PRICE }}</td>
                <td>{{ value.USD.HIGHDAY }}</td>
                <td>{{ value.USD.LOWDAY }}</td>
                <td>{{ value.USD.MKTCAP }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {#      Crypto Price Table End     #}

    {#      News Cards Start     #}
    <div class="container">
        <div class="row">
            {% for element in news.Data %}
                <div class="col-sm">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{element.imageurl}}" alt="{{element.source}}">
                        <div class="card-body">
                            <h5 class="card-title">{{element.title}}</h5>
                            <p class="card-text">{{api.body}}</p>
                            <a href="{{ x.url }}" class="btn btn-secondary">Read More...</a>
                        </div>
                    </div>
                    <br/>
                </div>
            {% endfor %}
        </div>
    </div>
    {#      News Cards End     #}

{% endblock %}

templates/search_prices.html
{% extends 'base.html' %}

{% block content %}
    {#      Price Jumbotron Start     #}
    <div class="jumbotron">
        {% if message  %}
            <h3>{{ message }}</h3>
        {% else %}
            {% if crypto.Response %}
                <h6>Sorry <strong>{{ quotes }}</strong> does not exist. Pleas Try Again...</h6>
            {% else %}
                <h5>Price Search Result for:</h5>
                <h1 class=display-4">{{quotes}}</h1>
            {% endif %}
        {% endif %}
    </div>
    {#      Price Jumbotron end     #}

    {% if not message  %}

        {#      Crypto Price Table Start     #}
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th scope="col">Crypto</th>
                <th scope="col">USD</th>
                <th scope="col">BDT</th>
                <th scope="col">24h High</th>
                <th scope="col">24h Low</th>
                <th scope="col">Market Cap</th>
            </tr>
            </thead>
            <tbody>
            {% for key,value in crypto.DISPLAY.items %}
                <tr>
                    <td>{{key}}</td>
                    <td>{{ value.USD.PRICE }}</td>
                    <td>{{ value.BDT.PRICE }}</td>
                    <td>{{ value.USD.HIGHDAY }}</td>
                    <td>{{ value.USD.LOWDAY }}</td>
                    <td>{{ value.USD.MKTCAP }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {#      Crypto Price Table End     #}
    {% endif %}

{% endblock %}